services:
  back:
    build:
      context: ./backend
    volumes:
      - ./back:/app
    working_dir:
      /app
    command: cargo watch -x run

    ports:
      - "8000:8000"
    restart: unless-stopped

    depends_on:
      - database

  front:
    image: node:20
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    restart: unless-stopped
    
    depends_on:
      - back

  batabase:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: