services:
  back:
    build:
      context: ./back
    volumes:
      - ./back:/app
    working_dir: /app
    env_file:
      - back.env

    command: cargo watch -x run
    expose:
      - "8080"
    restart: unless-stopped

    depends_on:
      - database

  front:
    image: node:20
    volumes:
      - ./front:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    expose:
      - "3000"

    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379"
    volumes:
      - redis_data:/data

    

  database:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./back:/app
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - back
      - front
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: